### PR TITLE
fix(alacritty): update template to toml

### LINKED ISSUE #88: Update alacritty template
Alacritty switched its config format from yaml to toml a while ago. The template in [build.lua](../tree/master/lua/melange/build.lua) should be updated accordingly.

### PR DESCRIPTION
**Pull request by DimitrisDimitropoulos**
I have updated the template to toml from yml. I have tested the output. However I am not really sure if the output is expected to be in the repo. Feel free to change anything.

---

Closes #88

### CODE REVIEW

File: lua/melange/build.lua [hunk 1]
```diff
@@ -145,36 +145,35 @@ end
...
+white = "$white"
+[colors.bright]
+black = "$bright_black"
+red = "$bright_red"
+green = "$bright_green"
+yellow = "$bright_yellow"
+blue = "$bright_blue"
+magenta = "$bright_magenta"
+cyan = "$bright_cyan"
+white = "$bright_white"
```
Comment (savq) [inline lua/melange/build.lua:176]: Could you align the equal signs here? Makes the template look tidier.

**Review by savq — CHANGES_REQUESTED** [review]

**Comment by savq** [comment]
The output should be in the repo. We could generate it on-demand, but I think most people just copy-paste it directly from github.
